version: '3.8'

services:
  buddhabrot:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"
