version: '3.8'

services:
  buddhabrot:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
