version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - plots:/plots
    healthcheck:
      test: curl --fail http://localhost:3000/api/healthcheck || exit 1
      interval: 15s
      timeout: 30s
      retries: 3

  plotter:
    build:
      context: .
      dockerfile: ./plotter/Dockerfile
    depends_on:
      - api
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - plots:/plots

  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 15s
      timeout: 30s
      retries: 3

  # Hat tip to https://cimentadaj.github.io/blog/2020-11-25-deploying-mysql-database-using-docker/deploying-mysql-database-using-docker/
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./mysql/sql:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
    healthcheck:
    # https://stackoverflow.com/a/51641089/2382333
      test: /usr/bin/mysql --user=root --password=$DB_ROOT_PASSWORD --execute "SHOW DATABASES;"
      interval: 15s
      timeout: 30s
      retries: 3

# https://github.com/docker-library/mysql/issues/302
# https://stackoverflow.com/a/65348042
volumes:
  mysql-data:
  plots:
