CREATE DATABASE buddhabrot;

FLUSH PRIVILEGES;

USE buddhabrot;

CREATE TABLE plots (
    id BIGINT NOT NULL AUTO_INCREMENT,
    plot JSON NOT NULL,
    img MEDIUMBLOB NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
